name: Build and Publish Docker Image
on:
  push:
    tags:
      - 'sv*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Set Versions
        uses: actions/github-script@v4
        id: set_version
        with:
          script: |
            const tag = context.ref.substring(10)
            const no_v = tag.replace('sv', '')
            const dash_index = no_v.lastIndexOf('-')
            const no_dash = (dash_index > -1) ?  no_v.substring(0, dash_index) : no_v
            core.setOutput('tag', tag)
            core.setOutput('no-v', no_v)
            core.setOutput('no-dash', no_dash)

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          file: ./Dockerfile
          build-args: |
            PORT=${{ vars.APP_PORT }}
            DB_HOST=${{ vars.DB_HOST }}
            DB_PORT=${{ vars.DB_PORT }}
            DB_USERNAME=${{ secrets.DB_USERNAME }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_NAME=${{ vars.DB_NAME }}
            BASE_FRONT_URL=${{ vars.BASE_FRONT_URL }}
            SMTP_LOGIN=${{ secrets.SMTP_LOGIN }}
            SMTP_PASS=${{ secrets.SMTP_PASS }}
            SMTP_SERVER=${{ vars.SMTP_SERVER }}
            EMAIL_SENDER=${{ vars.EMAIL_SENDER }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_EXPIRATION_TIME=${{ vars.JWT_EXPIRATION_TIME }}
            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
            GOOGLE_CALLBACK_URL=${{ vars.GOOGLE_CALLBACK_URL }}
          tags: |
            medonproject/medon:${{ steps.set_version.outputs.no-dash }}
            medonproject/medon:latest